### ISSUE TITLE
Misplaced space(s) around '|' sign.

### ISSUE THREAD

**Issue by CorentinB** [ronanboiteau/NormEZ#2]
Hi, with this kind of code:

`my_putchar('|');`

I get this error:

> Misplaced space(s) around '|' sign.

You should consider avoid this warning when there are quotes around the pipe. :)

**Comment by ronanboiteau** [comment]
Hello! As explained [in the Known Issues](https://github.com/ronanboiteau/NormEZ#known-issues): context is not handled by NormEZ. It means NormEZ doesn't make the difference between strings, characters, comments & code.

**Comment by ronanboiteau** [comment]
Commit [8c16f4b88da36fa38b401157cc94110c41e0b60b](https://github.com/ronanboiteau/NormEZ/commit/8c16f4b88da36fa38b401157cc94110c41e0b60b) fixes this issue.
