### ISSUE TITLE
Failed to detect when body of function > 20 lines

### ISSUE THREAD

**Issue by selena81792** [ronanboiteau/NormEZ#20]
NormEZ did not warn about the length of this function, very sad

```c
int	my_getnbr(char *str)
{
    int negative_multiplier;
    unsigned long long int storage;

    negative_multiplier = 1;
    storage = 0;
    while (*str && *str != '\0' && (*str == '+' || *str == '-')){
        if (*str == '-') negative_multiplier *= -1;
        str++;
    }
    while (*str && *str != '\0' && (*str >= '0' && *str <= '9')){
        if (storage > 214748364){
            return 0;
        }
        storage = storage*10 + *str-48;
        str++;
    }
    if (negative_multiplier == -1 && storage > 2147483648){
        return 0;
    } else if (negative_multiplier == 1 && storage > 2147483647){
        return 0;
    }
    storage *= negative_multiplier;
    return (storage);
}
```

**Comment by ronanboiteau** [comment]
That's because you have to respect the **L4 - Curly brackets** article of the coding style in order for the line check to work.

As an example, the following:

```c
while (*str && *str != '\0' && (*str == '+' || *str == '-')){
        [...]
    }
```

...should be:

```c
while (*str && *str != '\0' && (*str == '+' || *str == '-'))
    {
        [...]
    }
```

Once you've fix this, the line check will work fine.

**Comment by ronanboiteau** [comment]
That's the downside of "regex parsing". Since I don't use a real parser, I have to base the check on something. For the line check, I used the opening and closing curly brackets, because I know that they're always supposed to be alone on their line.

**Comment by selena81792** [comment]
The rule of L4 has changed now, they want us to put all curly backets on the end of the line (except with functions)

New rule screenshot: https://i.imgur.com/NHKl7J4.png

This is a pity, because it sounds like there will be a lot of work to change the bot to meet the new rules now...

**Comment by Nafiros** [comment]
this issues seems to be fixed...
