### ISSUE TITLE
Misplaced space(s) around '++' sign and Wrong Tabulation in Makefile

### ISSUE THREAD

**Issue by hugojeanmaire1** [ronanboiteau/NormEZ#22]
Hello,

When i make nb++ for example, but NormEZ tells me that I have misplaced space(s) around '++' sign, but only there aren't misplaced space(s) around this with this code as for example: 
    if (test_neg1 == 1) {
        my_putchar('-');
        nb1++;
        nb2++;
    }

And in Makefile, there are tabulation, but NormEZ wait for spaces

**Comment by bitdriftr** [comment]
Indentation check in Makefile fixed in #24

**Comment by ronanboiteau** [comment]
Thanks for the fix! I merged it with the master branch 👍
