### ISSUE TITLE
Forbidden functions are not part of the coding style

### ISSUE THREAD

**Issue by lodi-g** [ronanboiteau/NormEZ#6]
Forbidden functions are not part of the coding style but are per-project and thus cannot be detected should not be detected in a general checker.

**Comment by ronanboiteau** [comment]
I think it's better for NormEZ to flag possible forbidden functions in its default behavior. It can really save a project.  However I'm working on an option to disable forbidden functions warnings.

**Comment by lodi-g** [comment]
I was just talking about the Single Resposibility Principle - actually it may reveal useful to check for forbidden functions - forbidden functions are just not in the coding style so maybe you'd pick a more broad name and description.

**Comment by ronanboiteau** [comment]
Feature added by [this pull request](https://github.com/ronanboiteau/NormEZ/pull/12).
