### ISSUE TITLE
[Question] Misplaced comment

### ISSUE THREAD

**Issue by Hinara** [ronanboiteau/NormEZ#9]
What is misplaced comment error ?
I don't see anything like that in the coding style.

**Comment by ronanboiteau** [comment]
Section **F6 - Comments inside a function**, page 7 of the coding-style PDF:

![Comments inside a function](https://user-images.githubusercontent.com/3595480/36508158-2b7b67f8-175c-11e8-99a8-789938bd3005.png)

**Comment by Hinara** [comment]
OK,
However when I do a comment in my header file I also get "Misplaced comment"
Example:
```c
/*
** EPITECH PROJECT, 2018
** TEST
** File description:
** TEST
*/

#ifndef TEST_H_
	#define TEST_H_
	#include <stdlib.h>

typedef struct	test_s {
	char	test;
}		test_t;

/* Why ?? */
#endif
```

**Comment by Hinara** [comment]
By the way I think a message like juste the title of the coding style L6 "Comment inside a function" would be better than misplaced has it's tells you why the comment is misplaced.

**Comment by Hinara** [comment]
The bad regex is :
https://github.com/ronanboiteau/NormEZ/blob/master/NormEZ.rb#L453

**Comment by Hinara** [comment]
Same in .c with a simple if else
```c
/*
** EPITECH PROJECT, 2018
** TEST
** File description:
** TEST
*/

int main(void)
{
	if (1) {
		return (0);
	} else {
		return (1);
	}
}
/* Here too */
```
